
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    interpolation_method: splines
    allow_partial_joints_goal: false
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.05
      left_joint_1: { trajectory: 0.80, goal: 0.05 }
      left_joint_2: { trajectory: 0.80, goal: 0.05 }
      left_joint_3: { trajectory: 0.80, goal: 0.05 }
      left_joint_4: { trajectory: 0.80, goal: 0.05 }
      left_joint_5: { trajectory: 0.80, goal: 0.05 }
      left_joint_6: { trajectory: 0.80, goal: 0.05 }

right_arm_controller:
  ros__parameters:
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    interpolation_method: splines
    allow_partial_joints_goal: false
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.05
      right_joint_1: { trajectory: 0.80, goal: 0.05 }
      right_joint_2: { trajectory: 0.80, goal: 0.05 }
      right_joint_3: { trajectory: 0.80, goal: 0.05 }
      right_joint_4: { trajectory: 0.80, goal: 0.05 }
      right_joint_5: { trajectory: 0.80, goal: 0.05 }
      right_joint_6: { trajectory: 0.80, goal: 0.05 }
