<?xml version="1.0"?>
<package format="3">
  <name>d455_6d_pose</name>
  <version>0.1.0</version>
  <description>Independent RGB-D 6D pose estimation for D455, bottles and RoboMaster energy units.</description>
  <maintainer email="hydarealman@gmail.com">hydarealman</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>cv_bridge</depend>
  <depend>diagnostic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>libopencv-dev</depend>
  <depend>message_filters</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>vision_msgs</depend>
  <depend>visualization_msgs</depend>
  <exec_depend>realsense2_camera</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
